# Generated by Django 5.0.6 on 2024-11-11 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0006_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 16, 26, 40, 885881, tzinfo=datetime.timezone.utc)),
        ),
    ]
